#!/usr/bin/env python3
"""tools/render_video.py — assemble episode MP4 from images + segmented narration.

Usage:
    python tools/render_video.py <video-slug>

Reads:
    assets/<slug>/img_NN.jpg           — generated by tools/generate_images.py
    assets/<slug>/segment_NN_*.mp3     — generated by tools/narrate.py
    assets/<slug>/segments.json        — narration manifest

Produces:
    assets/<slug>/narration.mp3        — concatenated full narration
    assets/<slug>/final.mp4            — 1080p video with Ken Burns pan/zoom

Uses the ffmpeg binary bundled with imageio-ffmpeg (no system ffmpeg required).

Visual strategy: equal-time image cycling matched to narration duration,
with Ken Burns pan/zoom on each image. Not fancy, but ships. Future
improvement: read a real storyboard.json mapping images to beats.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import imageio_ffmpeg  # type: ignore

ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = ROOT / "experiments" / "youtube-history-channel" / "assets"

FFMPEG = imageio_ffmpeg.get_ffmpeg_exe()
FFPROBE = FFMPEG.replace("ffmpeg", "ffprobe") if "ffprobe" in FFMPEG else FFMPEG

OUTPUT_RES = "1920x1080"
FPS = 30


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=check, capture_output=True, text=True)


def audio_duration(path: Path) -> float:
    """Return audio duration in seconds using ffmpeg stderr parsing
    (avoids needing ffprobe separately)."""
    result = subprocess.run(
        [FFMPEG, "-i", str(path), "-hide_banner"],
        capture_output=True,
        text=True,
    )
    # ffmpeg prints 'Duration: HH:MM:SS.ss' on stderr
    import re
    m = re.search(r"Duration:\s+(\d+):(\d+):(\d+\.\d+)", result.stderr)
    if not m:
        raise RuntimeError(f"could not parse duration of {path}: {result.stderr[:500]}")
    h, mi, s = m.groups()
    return int(h) * 3600 + int(mi) * 60 + float(s)


def concat_audio_segments(segments_dir: Path, manifest: dict, out_path: Path) -> None:
    """Concatenate all segment MP3s in manifest order into one narration.mp3."""
    # ffmpeg concat demuxer needs an input list file
    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False, encoding="utf-8") as f:
        list_path = Path(f.name)
        for seg in manifest["segments"]:
            seg_file = segments_dir / seg["file"]
            if not seg_file.exists():
                print(f"  warn: missing segment file {seg_file.name}, skipping", file=sys.stderr)
                continue
            # concat demuxer needs forward slashes and escaped quotes
            f.write(f"file '{seg_file.as_posix()}'\n")
    try:
        run([
            FFMPEG, "-y", "-f", "concat", "-safe", "0",
            "-i", str(list_path),
            "-c:a", "libmp3lame", "-b:a", "192k",
            str(out_path),
        ])
    finally:
        list_path.unlink(missing_ok=True)


def build_video(image_paths: list[Path], narration: Path, out_path: Path) -> None:
    """Build the final video: Ken Burns pan/zoom per image, equal time
    slices sized to match the narration length, mux with narration audio."""
    total_duration = audio_duration(narration)
    n_images = len(image_paths)
    if n_images == 0:
        raise RuntimeError("no images to render")

    per_image = total_duration / n_images
    # Ken Burns with zoompan: start at zoom 1.0, end at zoom 1.15 over the shot duration
    # Zoompan works on integer frames — multiply by FPS
    frames_per_shot = int(round(per_image * FPS))
    # Alternate zoom direction per image for variety
    # zoompan filter: z='zoom+0.0015' (zoom in), z='if(eq(on,0),1.15,zoom-0.0015)' (zoom out)

    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        # Render each image to an individual MP4 clip, then concat
        clip_paths: list[Path] = []
        for idx, img in enumerate(image_paths):
            clip = td_path / f"clip_{idx:02d}.mp4"
            direction = "in" if idx % 2 == 0 else "out"
            if direction == "in":
                zoom_expr = "min(zoom+0.0012,1.18)"
            else:
                zoom_expr = "if(lte(zoom,1.0),1.18,max(zoom-0.0012,1.0))"
            # Build zoompan filter
            filter_complex = (
                f"scale=3840:2160:force_original_aspect_ratio=decrease,"
                f"pad=3840:2160:(ow-iw)/2:(oh-ih)/2:color=black,"
                f"zoompan=z='{zoom_expr}':"
                f"d={frames_per_shot}:"
                f"x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':"
                f"s={OUTPUT_RES}:fps={FPS}"
            )
            run([
                FFMPEG, "-y", "-loop", "1", "-i", str(img),
                "-vf", filter_complex,
                "-t", f"{per_image:.3f}",
                "-c:v", "libx264", "-preset", "fast", "-crf", "20",
                "-pix_fmt", "yuv420p",
                str(clip),
            ])
            clip_paths.append(clip)
            print(f"  clip {idx+1}/{n_images}: {img.name} ({per_image:.1f}s, zoom-{direction})")

        # Concat all clips
        concat_list = td_path / "concat.txt"
        with concat_list.open("w", encoding="utf-8") as f:
            for clip in clip_paths:
                f.write(f"file '{clip.as_posix()}'\n")
        silent_video = td_path / "silent.mp4"
        run([
            FFMPEG, "-y", "-f", "concat", "-safe", "0",
            "-i", str(concat_list),
            "-c", "copy",
            str(silent_video),
        ])

        # Mux silent video with narration audio
        run([
            FFMPEG, "-y",
            "-i", str(silent_video),
            "-i", str(narration),
            "-map", "0:v", "-map", "1:a",
            "-c:v", "copy",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest",
            str(out_path),
        ])


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: render_video.py <video-slug>")
    slug = sys.argv[1]

    assets = ASSETS_DIR / slug
    if not assets.is_dir():
        sys.exit(f"error: {assets} does not exist")

    # Collect images in numerical order
    image_paths = sorted(assets.glob("img_*.jpg"))
    if not image_paths:
        sys.exit(f"error: no img_*.jpg in {assets}")

    segments_json = assets / "segments.json"
    if not segments_json.exists():
        sys.exit(f"error: {segments_json} missing — run narrate.py first")
    manifest = json.loads(segments_json.read_text(encoding="utf-8"))

    narration = assets / "narration.mp3"
    print(f"Concatenating {len(manifest['segments'])} segments -> {narration.name}")
    concat_audio_segments(assets, manifest, narration)

    final = assets / "final.mp4"
    print(f"\nRendering {len(image_paths)} images -> {final.name}")
    build_video(image_paths, narration, final)

    print(f"\ndone: {final}")
    print(f"size: {final.stat().st_size / 1_000_000:.1f} MB")


if __name__ == "__main__":
    main()
